In [33]:
import numpy as np

In [34]:
data = np.random.randint(1,101,size=(4,4))
print(data)

[[83  5 63 46]
 [60 27  7 59]
 [84 70 55 16]
 [13 88 65  2]]


In [35]:
print(data.sum())

743


In [36]:
print(data.min())

2


In [37]:
print(data.max())

88


In [38]:
data[data%2==0]=0

In [39]:
print(data)

[[83  5 63  0]
 [ 0 27  7 59]
 [ 0  0 55  0]
 [13  0 65  0]]


In [40]:
np.sum(data,axis=1)

array([151,  93,  55,  78])

In [41]:
data.transpose()

array([[83,  0,  0, 13],
       [ 5, 27,  0,  0],
       [63,  7, 55, 65],
       [ 0, 59,  0,  0]])