In [1]:
import numpy as np

In [2]:
data = np.random.randint(1,101,size=(4,4))
print(data)

[[ 8  9 25 80]
 [ 1 20 13 44]
 [61  4 54 84]
 [17 32 87 27]]


In [3]:
print(data.sum())

566


In [4]:
print(data.min())

1


In [5]:
print(data.max())

87


In [6]:
data[data%2==0]=0

In [7]:
print(data)

[[ 0  9 25  0]
 [ 1  0 13  0]
 [61  0  0  0]
 [17  0 87 27]]


In [8]:
np.sum(data,axis=1)

array([ 34,  14,  61, 131])

In [11]:
data = data.transpose()
print(data)

[[ 0  1 61 17]
 [ 9  0  0  0]
 [25 13  0 87]
 [ 0  0  0 27]]


## Broadcasting operations

In [30]:
## converting the data into a numpy array
arr1 = np.array(data)
print(arr1)

[[ 0  1 61 17]
 [ 9  0  0  0]
 [25 13  0 87]
 [ 0  0  0 27]]


In [31]:
## Adding a constant value to the arr1
arr1 = arr1+5
print(arr1)

[[ 5  6 66 22]
 [14  5  5  5]
 [30 18  5 92]
 [ 5  5  5 32]]


In [19]:
# subtracting a vector [1,2,3,4] from each row of the matrix
arr2 = np.array([1,2,3,4])
subarr = arr1-arr2
print(subarr)

[[ 4  4 63 18]
 [13  3  2  1]
 [29 16  2 88]
 [ 4  3  2 28]]


In [32]:
# multiply a column vector [1,2,3,4] from each column of the matrix
arr3 = np.array([[1],[2],[3],[4]])
print(arr3)
mularr = arr1*arr3
print(mularr)

[[1]
 [2]
 [3]
 [4]]
[[  5   6  66  22]
 [ 28  10  10  10]
 [ 90  54  15 276]
 [ 20  20  20 128]]


In [28]:
# subtracting the mean of each row from the matrix
meanarr = np.mean(arr1,axis=1)
print(meanarr)

[24.75  7.25 36.25 11.75]


In [34]:
print(arr1)
submean = arr1-meanarr.reshape(-1, 1)
print(submean)

[[ 5  6 66 22]
 [14  5  5  5]
 [30 18  5 92]
 [ 5  5  5 32]]
[[-19.75 -18.75  41.25  -2.75]
 [  6.75  -2.25  -2.25  -2.25]
 [ -6.25 -18.25 -31.25  55.75]
 [ -6.75  -6.75  -6.75  20.25]]
